# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animeinfo', '0002_auto_20170528_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='animeinfo',
            name='period_type',
            field=models.CharField(choices=[('year', 'Year'), ('decade', 'Decade')], default='decade', max_length=50),
        ),
    ]
