# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animeinfo', '0004_auto_20170528_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animeinfo',
            name='image',
            field=models.ImageField(upload_to='files/animeinfo'),
        ),
    ]
