# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animeinfo', '0005_auto_20170528_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animeinfo',
            name='genre',
            field=models.CharField(choices=[('all', 'All'), ('action', 'Action'), ('adventure', 'Adventure'), ('comedy', 'Comedy'), ('drama', 'Drama'), ('sci-fi', 'Sci-fi'), ('space', 'Space'), ('mistery', 'Mistery'), ('supernatural', 'Supernatural'), ('police', 'Police')], default='all', max_length=50),
        ),
    ]
