# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animeinfo', '0006_auto_20170528_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='animeinfo',
            name='description2',
            field=models.TextField(default=''),
        ),
    ]
